# coding: utf-8

from __future__ import absolute_import
from datetime import date, datetime  # noqa: F401

from typing import List, Dict  # noqa: F401

from swagger_server.models.base_model_ import Model
from swagger_server.models.kernels import Kernels  # noqa: F401,E501
from swagger_server.models.missions import Missions  # noqa: F401,E501
from swagger_server import util


class FileInner(Model):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """

    def __init__(self, name: str=None, kernel: Kernels=None, mission: Missions=None, contents: str=None):  # noqa: E501
        """FileInner - a model defined in Swagger

        :param name: The name of this FileInner.  # noqa: E501
        :type name: str
        :param kernel: The kernel of this FileInner.  # noqa: E501
        :type kernel: Kernels
        :param mission: The mission of this FileInner.  # noqa: E501
        :type mission: Missions
        :param contents: The contents of this FileInner.  # noqa: E501
        :type contents: str
        """
        self.swagger_types = {
            'name': str,
            'kernel': Kernels,
            'mission': Missions,
            'contents': str
        }

        self.attribute_map = {
            'name': 'name',
            'kernel': 'kernel',
            'mission': 'mission',
            'contents': 'contents'
        }

        self._name = name
        self._kernel = kernel
        self._mission = mission
        self._contents = contents

    @classmethod
    def from_dict(cls, dikt) -> 'FileInner':
        """Returns the dict as a model

        :param dikt: A dict.
        :type: dict
        :return: The File_inner of this FileInner.  # noqa: E501
        :rtype: FileInner
        """
        return util.deserialize_model(dikt, cls)

    @property
    def name(self) -> str:
        """Gets the name of this FileInner.


        :return: The name of this FileInner.
        :rtype: str
        """
        return self._name

    @name.setter
    def name(self, name: str):
        """Sets the name of this FileInner.


        :param name: The name of this FileInner.
        :type name: str
        """

        self._name = name

    @property
    def kernel(self) -> Kernels:
        """Gets the kernel of this FileInner.


        :return: The kernel of this FileInner.
        :rtype: Kernels
        """
        return self._kernel

    @kernel.setter
    def kernel(self, kernel: Kernels):
        """Sets the kernel of this FileInner.


        :param kernel: The kernel of this FileInner.
        :type kernel: Kernels
        """

        self._kernel = kernel

    @property
    def mission(self) -> Missions:
        """Gets the mission of this FileInner.


        :return: The mission of this FileInner.
        :rtype: Missions
        """
        return self._mission

    @mission.setter
    def mission(self, mission: Missions):
        """Sets the mission of this FileInner.


        :param mission: The mission of this FileInner.
        :type mission: Missions
        """

        self._mission = mission

    @property
    def contents(self) -> str:
        """Gets the contents of this FileInner.


        :return: The contents of this FileInner.
        :rtype: str
        """
        return self._contents

    @contents.setter
    def contents(self, contents: str):
        """Sets the contents of this FileInner.


        :param contents: The contents of this FileInner.
        :type contents: str
        """

        self._contents = contents
