# coding: utf-8

from __future__ import absolute_import
from datetime import date, datetime  # noqa: F401

from typing import List, Dict  # noqa: F401

from swagger_server.models.base_model_ import Model
from swagger_server import util


class MetakernelsInner(Model):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """

    def __init__(self, id: int=None, name: str=None, newest: bool=None, path: str=None, year: object=None):  # noqa: E501
        """MetakernelsInner - a model defined in Swagger

        :param id: The id of this MetakernelsInner.  # noqa: E501
        :type id: int
        :param name: The name of this MetakernelsInner.  # noqa: E501
        :type name: str
        :param newest: The newest of this MetakernelsInner.  # noqa: E501
        :type newest: bool
        :param path: The path of this MetakernelsInner.  # noqa: E501
        :type path: str
        :param year: The year of this MetakernelsInner.  # noqa: E501
        :type year: object
        """
        self.swagger_types = {
            'id': int,
            'name': str,
            'newest': bool,
            'path': str,
            'year': object
        }

        self.attribute_map = {
            'id': 'id',
            'name': 'name',
            'newest': 'newest',
            'path': 'path',
            'year': 'year'
        }

        self._id = id
        self._name = name
        self._newest = newest
        self._path = path
        self._year = year

    @classmethod
    def from_dict(cls, dikt) -> 'MetakernelsInner':
        """Returns the dict as a model

        :param dikt: A dict.
        :type: dict
        :return: The Metakernels_inner of this MetakernelsInner.  # noqa: E501
        :rtype: MetakernelsInner
        """
        return util.deserialize_model(dikt, cls)

    @property
    def id(self) -> int:
        """Gets the id of this MetakernelsInner.


        :return: The id of this MetakernelsInner.
        :rtype: int
        """
        return self._id

    @id.setter
    def id(self, id: int):
        """Sets the id of this MetakernelsInner.


        :param id: The id of this MetakernelsInner.
        :type id: int
        """

        self._id = id

    @property
    def name(self) -> str:
        """Gets the name of this MetakernelsInner.


        :return: The name of this MetakernelsInner.
        :rtype: str
        """
        return self._name

    @name.setter
    def name(self, name: str):
        """Sets the name of this MetakernelsInner.


        :param name: The name of this MetakernelsInner.
        :type name: str
        """

        self._name = name

    @property
    def newest(self) -> bool:
        """Gets the newest of this MetakernelsInner.


        :return: The newest of this MetakernelsInner.
        :rtype: bool
        """
        return self._newest

    @newest.setter
    def newest(self, newest: bool):
        """Sets the newest of this MetakernelsInner.


        :param newest: The newest of this MetakernelsInner.
        :type newest: bool
        """

        self._newest = newest

    @property
    def path(self) -> str:
        """Gets the path of this MetakernelsInner.


        :return: The path of this MetakernelsInner.
        :rtype: str
        """
        return self._path

    @path.setter
    def path(self, path: str):
        """Sets the path of this MetakernelsInner.


        :param path: The path of this MetakernelsInner.
        :type path: str
        """

        self._path = path

    @property
    def year(self) -> object:
        """Gets the year of this MetakernelsInner.


        :return: The year of this MetakernelsInner.
        :rtype: object
        """
        return self._year

    @year.setter
    def year(self, year: object):
        """Sets the year of this MetakernelsInner.


        :param year: The year of this MetakernelsInner.
        :type year: object
        """

        self._year = year
